application: eblahm
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /syn.+
  login: admin
  script: urls.sync_agent
  secure: always

- url: .*
  script: urls.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"

builtins:
- remote_api: on
